#!/usr/bin/env python3
"""
Merges the 3 TypeScript outputs from Claude.ai into src/data/contexts.ts.

Usage:
  Save Claude's responses as:
    scripts/prompts/output_1.ts
    scripts/prompts/output_2.ts
    scripts/prompts/output_3.ts

  Then run:
    python scripts/merge_contexts.py
"""

import re
import os

OUTPUT_DIR = "scripts/prompts"
DEST = "src/data/contexts.ts"


def extract_entries(content):
    # Match lines like:   1: "...",
    return re.findall(r'^\s*(\d+):\s*("(?:[^"\\]|\\.)*"),\s*$', content, re.MULTILINE)


def main():
    all_entries = {}

    for i in range(1, 4):
        path = os.path.join(OUTPUT_DIR, f"output_{i}.ts")
        if not os.path.exists(path):
            print(f"Missing {path} — skipping.")
            continue
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        entries = extract_entries(content)
        print(f"output_{i}.ts: {len(entries)} entries found")
        for qid_str, value in entries:
            all_entries[int(qid_str)] = value

    if not all_entries:
        print("No entries found. Check that your output files contain valid TypeScript.")
        return

    lines = ["// Generated by scripts/merge_contexts.py",
             "export const contexts: Record<number, string> = {"]
    for qid in sorted(all_entries.keys()):
        lines.append(f"  {qid}: {all_entries[qid]},")
    lines.append("};\n")

    with open(DEST, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nWritten {len(all_entries)} contexts to {DEST}")
    missing = [i for i in range(1, 311) if i not in all_entries]
    if missing:
        print(f"Warning: missing IDs: {missing[:20]}{'...' if len(missing) > 20 else ''}")


if __name__ == "__main__":
    main()
